---
title: "primate_cov_matrix"
author: "Jenny Yijian Huang"
date: '2022-06-02'
output: html_document
---

# --------------------
# Creating the primate correlation matrix based on a phylogenetic tree.
# --------------------

```{r}
# Loading libraries.
library(ape)  # why are there more species here than nM?
# Loading Tree.
filename <- "consensus_chronogram.nex"
x <- read.nexus(paste0(filename)) 

# Primate tree
x_names <- x$tip.label
length(unique(as.character(x_names)))
####
# Debug2 
## Make sure names of tree match names of primates.
lstA <- unlist(uni_primates)
lstB <- unlist(unique(as.character(x_names)))
sharedtips <- intersect(lstA, lstB)

x_93 <- keep.tip(x, sharedtips)
x_93_names <- x_93$tip.label
length(unique(as.character(x_93_names)))
####

# Getting the correlation matrix:
this_cov <- ape::vcv(x_93, model = "Brownian", corr = TRUE) # This function computes the expected variances and covariances of a continuous trait assuming it evolves under a given model.
# https://pubmed.ncbi.nlm.nih.gov/10718731/

# Re-ordering to get species on the same order:
Cu_phylo <- this_cov[order(rownames(this_cov)), order(rownames(this_cov))]

# Dim correlation matrix
dim(Cu_phylo)

if (save_files) {
  save(Cu_phylo, file = paste0(save_path, 'Cu_phylo.dat'))
}
```

### Reference on ape::vcv:

Expected covariance under a Brownian model (Felsenstein 1985, Martins and Hansen 1997)
$$V_{ij} = \gamma \times t_a$$
where \(t_a\) is the distance on the phylogeny between the root and the most recent common ancestor of taxa \(i\) and \(j\) and \(\gamma\) is a constant.
```{r}
# Plot heatmap
gplots::heatmap.2(Cu_phylo, dendrogram = 'none', trace = 'none', Rowv = FALSE, Colv = FALSE,
                  labRow = FALSE, labCol = FALSE)
```


